-- Candy: a neovim colorscheme derived from the kitty tab bar palette.
--
-- Generated from the same OKLCH derivation that produces the tab bar's ten
-- candies, with L and C redistributed per semantic role. Do not hand-edit the
-- hexes in palette.lua -- regenerate, or the equal-weight property that makes
-- the set cohere quietly breaks.

local M = {}

local C = require("r35.themes.candy.palette")

---Apply the colorscheme.
function M.load()
  if vim.g.colors_name then
    vim.cmd("hi clear")
  end
  vim.o.termguicolors = true
  vim.o.background = "dark"
  vim.g.colors_name = "candy"

  local set = vim.api.nvim_set_hl
  for group, spec in pairs(M.groups()) do
    set(0, group, spec)
  end
  for i, colour in ipairs(C.terminal) do
    vim.g["terminal_color_" .. (i - 1)] = colour
  end
end

---All highlight groups, as a single table so they can be inspected or patched
---before being applied.
---@return table<string, table>
function M.groups()
  local g = {
  -- Editor
  ["Normal"] = { fg = C["fg"], bg = C["bg"] },
  ["NormalNC"] = { fg = C["fg"], bg = C["bg"] },
  ["NormalFloat"] = { fg = C["fg"], bg = C["bg_float"] },
  ["FloatBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["FloatTitle"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["ColorColumn"] = { bg = C["bg_cursorline"] },
  ["Conceal"] = { fg = C["fg_muted"] },
  ["Cursor"] = { fg = C["bg"], bg = C["fg"] },
  ["lCursor"] = { fg = C["bg"], bg = C["fg"] },
  ["CursorIM"] = { fg = C["bg"], bg = C["fg"] },
  ["CursorColumn"] = { bg = C["bg_cursorline"] },
  ["CursorLine"] = { bg = C["bg_cursorline"] },
  ["CursorLineNr"] = { fg = C["line_nr_active"], bold = true },
  ["LineNr"] = { fg = C["line_nr"] },
  ["LineNrAbove"] = { fg = C["line_nr"] },
  ["LineNrBelow"] = { fg = C["line_nr"] },
  ["SignColumn"] = { fg = C["line_nr"], bg = C["bg_gutter"] },
  ["FoldColumn"] = { fg = C["line_nr"], bg = C["bg_gutter"] },
  ["Folded"] = { fg = C["comment"], bg = C["bg_cursorline"] },
  ["Directory"] = { fg = C["function"] },
  ["EndOfBuffer"] = { fg = C["bg"] },
  ["VertSplit"] = { fg = C["border"] },
  ["WinSeparator"] = { fg = C["border"] },
  ["NonText"] = { fg = C["line_nr"] },
  ["Whitespace"] = { fg = C["line_nr"] },
  ["SpecialKey"] = { fg = C["line_nr"] },
  ["Title"] = { fg = C["function"], bold = true },
  ["Question"] = { fg = C["info"] },
  ["MoreMsg"] = { fg = C["info"] },
  ["ModeMsg"] = { fg = C["fg"], bold = true },
  ["MsgArea"] = { fg = C["fg"] },
  ["ErrorMsg"] = { fg = C["error"] },
  ["WarningMsg"] = { fg = C["warning"] },
  ["MatchParen"] = { fg = C["line_nr_active"], bg = C["bg_matchparen"], bold = true },
  ["QuickFixLine"] = { bg = C["bg_quickfix"], bold = true },
  ["Visual"] = { bg = C["bg_visual"] },
  ["VisualNOS"] = { bg = C["bg_visual"] },
  -- Search. CurSearch forces BOTH colours so it can never inherit an
  -- unreadable foreground -- see palette.lua.
  ["Search"] = { fg = C["fg"], bg = C["bg_search"] },
  ["IncSearch"] = { fg = C["fg_cursearch"], bg = C["bg_cursearch"], bold = true },
  ["CurSearch"] = { fg = C["fg_cursearch"], bg = C["bg_cursearch"], bold = true },
  ["Substitute"] = { fg = C["fg_cursearch"], bg = C["bg_cursearch"] },
  -- Popups
  ["Pmenu"] = { fg = C["fg"], bg = C["bg_float"] },
  ["PmenuSel"] = { bg = C["bg_pmenu_sel"], bold = true },
  ["PmenuKind"] = { fg = C["type"], bg = C["bg_float"] },
  ["PmenuKindSel"] = { fg = C["type"], bg = C["bg_pmenu_sel"] },
  ["PmenuExtra"] = { fg = C["comment"], bg = C["bg_float"] },
  ["PmenuExtraSel"] = { fg = C["comment"], bg = C["bg_pmenu_sel"] },
  ["PmenuSbar"] = { bg = C["bg_float"] },
  ["PmenuThumb"] = { bg = C["border"] },
  ["WildMenu"] = { bg = C["bg_pmenu_sel"] },
  -- Statusline and tabs
  ["StatusLine"] = { fg = C["fg_statusline"], bg = C["bg_statusline"] },
  ["StatusLineNC"] = { fg = C["line_nr"], bg = C["bg_statusline"] },
  ["TabLine"] = { fg = C["comment"], bg = C["bg_gutter"] },
  ["TabLineFill"] = { bg = C["bg_gutter"] },
  ["TabLineSel"] = { fg = C["bg"], bg = C["function"], bold = true },
  ["WinBar"] = { fg = C["comment"], bold = true },
  ["WinBarNC"] = { fg = C["line_nr"] },
  -- Diff
  ["DiffAdd"] = { bg = C["bg_diff_add"] },
  ["DiffChange"] = { bg = C["bg_diff_change"] },
  ["DiffDelete"] = { bg = C["bg_diff_delete"] },
  ["DiffText"] = { bg = C["bg_diff_text"], bold = true },
  ["Added"] = { fg = C["string"] },
  ["Changed"] = { fg = C["constant"] },
  ["Removed"] = { fg = C["error"] },
  -- Spell
  ["SpellBad"] = { undercurl = true, sp = C["error"] },
  ["SpellCap"] = { undercurl = true, sp = C["warning"] },
  ["SpellLocal"] = { undercurl = true, sp = C["info"] },
  ["SpellRare"] = { undercurl = true, sp = C["hint"] },
  -- Legacy syntax
  ["Comment"] = { fg = C["comment"], italic = true },
  ["Constant"] = { fg = C["constant"] },
  ["String"] = { fg = C["string"] },
  ["Character"] = { fg = C["string"] },
  ["Number"] = { fg = C["constant"] },
  ["Float"] = { fg = C["constant"] },
  ["Boolean"] = { fg = C["boolean"] },
  ["Identifier"] = { fg = C["fg"] },
  ["Function"] = { fg = C["function"] },
  ["Statement"] = { fg = C["keyword"] },
  ["Conditional"] = { fg = C["keyword"] },
  ["Repeat"] = { fg = C["keyword"] },
  ["Label"] = { fg = C["keyword"] },
  ["Operator"] = { fg = C["fg_muted"] },
  ["Keyword"] = { fg = C["keyword"] },
  ["Exception"] = { fg = C["keyword"] },
  ["PreProc"] = { fg = C["boolean"] },
  ["Include"] = { fg = C["keyword"] },
  ["Define"] = { fg = C["keyword"] },
  ["Macro"] = { fg = C["boolean"] },
  ["PreCondit"] = { fg = C["boolean"] },
  ["Type"] = { fg = C["type"] },
  ["StorageClass"] = { fg = C["keyword"] },
  ["Structure"] = { fg = C["type"] },
  ["Typedef"] = { fg = C["type"] },
  ["Special"] = { fg = C["boolean"] },
  ["SpecialChar"] = { fg = C["boolean"] },
  ["Tag"] = { fg = C["type"] },
  ["Delimiter"] = { fg = C["fg_muted"] },
  ["SpecialComment"] = { fg = C["comment"], bold = true },
  ["Debug"] = { fg = C["error"] },
  ["Underlined"] = { fg = C["info"], underline = true },
  ["Ignore"] = { fg = C["line_nr"] },
  ["Error"] = { fg = C["error"] },
  ["Todo"] = { fg = C["hint"], bg = C["bg_vt_hint"], bold = true },
  -- Diagnostics
  ["DiagnosticError"] = { fg = C["error"] },
  ["DiagnosticWarn"] = { fg = C["warning"] },
  ["DiagnosticInfo"] = { fg = C["info"] },
  ["DiagnosticHint"] = { fg = C["hint"] },
  ["DiagnosticOk"] = { fg = C["string"] },
  ["DiagnosticVirtualTextError"] = { fg = C["error"], bg = C["bg_vt_error"] },
  ["DiagnosticVirtualTextWarn"] = { fg = C["warning"], bg = C["bg_vt_warning"] },
  ["DiagnosticVirtualTextInfo"] = { fg = C["info"], bg = C["bg_vt_info"] },
  ["DiagnosticVirtualTextHint"] = { fg = C["hint"], bg = C["bg_vt_hint"] },
  ["DiagnosticUnderlineError"] = { undercurl = true, sp = C["error"] },
  ["DiagnosticUnderlineWarn"] = { undercurl = true, sp = C["warning"] },
  ["DiagnosticUnderlineInfo"] = { undercurl = true, sp = C["info"] },
  ["DiagnosticUnderlineHint"] = { undercurl = true, sp = C["hint"] },
  ["DiagnosticFloatingError"] = { fg = C["error"], bg = C["bg_float"] },
  ["DiagnosticFloatingWarn"] = { fg = C["warning"], bg = C["bg_float"] },
  ["DiagnosticFloatingInfo"] = { fg = C["info"], bg = C["bg_float"] },
  ["DiagnosticFloatingHint"] = { fg = C["hint"], bg = C["bg_float"] },
  ["DiagnosticSignError"] = { fg = C["error"], bg = C["bg_gutter"] },
  ["DiagnosticSignWarn"] = { fg = C["warning"], bg = C["bg_gutter"] },
  ["DiagnosticSignInfo"] = { fg = C["info"], bg = C["bg_gutter"] },
  ["DiagnosticSignHint"] = { fg = C["hint"], bg = C["bg_gutter"] },
  ["DiagnosticDeprecated"] = { strikethrough = true, sp = C["comment"] },
  ["DiagnosticUnnecessary"] = { fg = C["line_nr"] },
  -- LSP
  ["LspReferenceText"] = { bg = C["bg_visual"] },
  ["LspReferenceRead"] = { bg = C["bg_visual"] },
  ["LspReferenceWrite"] = { bg = C["bg_visual"], underline = true },
  ["LspSignatureActiveParameter"] = { fg = C["parameter"], bold = true },
  ["LspInlayHint"] = { fg = C["line_nr"], bg = C["bg_cursorline"], italic = true },
  ["LspCodeLens"] = { fg = C["comment"], italic = true },
  ["LspInfoBorder"] = { fg = C["border"], bg = C["bg_float"] },

  -- Treesitter
  ["@variable"] = { fg = C["fg"] },
  ["@variable.builtin"] = { fg = C["boolean"] },
  ["@variable.parameter"] = { fg = C["parameter"] },
  ["@variable.member"] = { fg = C["field"] },
  ["@constant"] = { fg = C["constant"] },
  ["@constant.builtin"] = { fg = C["boolean"] },
  ["@constant.macro"] = { fg = C["boolean"] },
  ["@module"] = { fg = C["type"] },
  ["@module.builtin"] = { fg = C["type"] },
  ["@label"] = { fg = C["keyword"] },
  ["@string"] = { fg = C["string"] },
  ["@string.documentation"] = { fg = C["string"] },
  ["@string.regexp"] = { fg = C["boolean"] },
  ["@string.escape"] = { fg = C["boolean"], bold = true },
  ["@string.special"] = { fg = C["boolean"] },
  ["@string.special.url"] = { fg = C["info"], underline = true },
  ["@character"] = { fg = C["string"] },
  ["@character.special"] = { fg = C["boolean"] },
  ["@number"] = { fg = C["constant"] },
  ["@number.float"] = { fg = C["constant"] },
  ["@boolean"] = { fg = C["boolean"] },
  ["@type"] = { fg = C["type"] },
  ["@type.builtin"] = { fg = C["type"], italic = true },
  ["@type.definition"] = { fg = C["type"] },
  ["@attribute"] = { fg = C["boolean"] },
  ["@property"] = { fg = C["field"] },
  ["@function"] = { fg = C["function"] },
  ["@function.builtin"] = { fg = C["function"], italic = true },
  ["@function.call"] = { fg = C["function"] },
  ["@function.macro"] = { fg = C["boolean"] },
  ["@function.method"] = { fg = C["function"] },
  ["@function.method.call"] = { fg = C["function"] },
  ["@constructor"] = { fg = C["type"] },
  ["@operator"] = { fg = C["fg_muted"] },
  ["@keyword"] = { fg = C["keyword"] },
  ["@keyword.function"] = { fg = C["keyword"] },
  ["@keyword.operator"] = { fg = C["keyword"] },
  ["@keyword.import"] = { fg = C["keyword"] },
  ["@keyword.type"] = { fg = C["keyword"] },
  ["@keyword.modifier"] = { fg = C["keyword"] },
  ["@keyword.repeat"] = { fg = C["keyword"] },
  ["@keyword.return"] = { fg = C["keyword"], bold = true },
  ["@keyword.debug"] = { fg = C["error"] },
  ["@keyword.exception"] = { fg = C["keyword"] },
  ["@keyword.conditional"] = { fg = C["keyword"] },
  ["@keyword.directive"] = { fg = C["boolean"] },
  ["@punctuation.delimiter"] = { fg = C["fg_muted"] },
  ["@punctuation.bracket"] = { fg = C["fg_muted"] },
  ["@punctuation.special"] = { fg = C["boolean"] },
  ["@comment"] = { fg = C["comment"], italic = true },
  -- Coloured text on a faint tint, not an inverted badge: neorg links real
  -- content at these, where a solid slab swallows the line.
  ["@comment.error"] = { fg = C["error"], bg = C["bg_vt_error"], bold = true },
  ["@comment.warning"] = { fg = C["warning"], bg = C["bg_vt_warning"], bold = true },
  ["@comment.todo"] = { fg = C["hint"], bg = C["bg_vt_hint"], bold = true },
  ["@comment.note"] = { fg = C["info"], bg = C["bg_vt_info"], bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = C["function"], bold = true },
  ["@markup.quote"] = { fg = C["comment"], italic = true },
  ["@markup.math"] = { fg = C["boolean"] },
  ["@markup.link"] = { fg = C["info"] },
  ["@markup.link.label"] = { fg = C["field"] },
  ["@markup.link.url"] = { fg = C["info"], underline = true },
  ["@markup.raw"] = { fg = C["string"] },
  ["@markup.list"] = { fg = C["keyword"] },
  ["@markup.list.checked"] = { fg = C["string"] },
  ["@markup.list.unchecked"] = { fg = C["comment"] },
  ["@diff.plus"] = { fg = C["string"] },
  ["@diff.minus"] = { fg = C["error"] },
  ["@diff.delta"] = { fg = C["constant"] },
  ["@tag"] = { fg = C["keyword"] },
  ["@tag.builtin"] = { fg = C["keyword"] },
  ["@tag.attribute"] = { fg = C["parameter"] },
  ["@tag.delimiter"] = { fg = C["fg_muted"] },

  -- Neorg. Its todo markers link at @comment.* by default, which is meant
  -- for code tags; these state them directly instead.
  ["@neorg.todo_items.urgent"] = { fg = C["error"], bold = true },
  ["@neorg.todo_items.on_hold"] = { fg = C["info"] },
  ["@neorg.todo_items.uncertain"] = { fg = C["boolean"] },
  ["@neorg.todo_items.pending"] = { fg = C["constant"] },
  ["@neorg.todo_items.done"] = { fg = C["string"] },
  ["@neorg.todo_items.cancelled"] = { fg = C["line_nr"], strikethrough = true },
  ["@neorg.todo_items.recurring"] = { fg = C["keyword"] },
  ["@neorg.todo_items.undone"] = { fg = C["fg_muted"] },
  ["@neorg.markup.spoiler"] = { fg = C["fg_muted"], bg = C["fg_muted"] },

  -- Bufferline. Generated from state x severity; it darkens Normal
  -- on its own otherwise, which lands outside the palette.
  ["BufferLineFill"] = { fg = C["comment"], bg = C["bg_gutter"] },
  ["BufferLineBackground"] = { fg = C["comment"], bg = C["bg_gutter"] },
  ["BufferLineBufferVisible"] = { fg = C["fg_muted"], bg = C["bg_gutter"] },
  ["BufferLineBufferSelected"] = { fg = C["fg"], bg = C["bg"], bold = true },
  ["BufferLineNumbers"] = { fg = C["comment"], bg = C["bg_gutter"] },
  ["BufferLineNumbersVisible"] = { fg = C["fg_muted"], bg = C["bg_gutter"] },
  ["BufferLineNumbersSelected"] = { fg = C["line_nr_active"], bg = C["bg"], bold = true },
  ["BufferLineSeparator"] = { fg = C["bg_gutter"], bg = C["bg_gutter"] },
  ["BufferLineSeparatorVisible"] = { fg = C["bg_gutter"], bg = C["bg_gutter"] },
  ["BufferLineSeparatorSelected"] = { fg = C["bg_gutter"], bg = C["bg"] },
  ["BufferLineOffsetSeparator"] = { fg = C["border"], bg = C["bg_gutter"] },
  ["BufferLineIndicatorVisible"] = { fg = C["bg_gutter"], bg = C["bg_gutter"] },
  ["BufferLineIndicatorSelected"] = { fg = C["line_nr_active"], bg = C["bg"] },
  ["BufferLineModified"] = { fg = C["constant"], bg = C["bg_gutter"] },
  ["BufferLineModifiedVisible"] = { fg = C["constant"], bg = C["bg_gutter"] },
  ["BufferLineModifiedSelected"] = { fg = C["constant"], bg = C["bg"] },
  ["BufferLineDuplicate"] = { fg = C["line_nr"], bg = C["bg_gutter"], italic = true },
  ["BufferLineDuplicateVisible"] = { fg = C["line_nr"], bg = C["bg_gutter"], italic = true },
  ["BufferLineDuplicateSelected"] = { fg = C["fg_muted"], bg = C["bg"], italic = true },
  ["BufferLineCloseButton"] = { fg = C["comment"], bg = C["bg_gutter"] },
  ["BufferLineCloseButtonVisible"] = { fg = C["fg_muted"], bg = C["bg_gutter"] },
  ["BufferLineCloseButtonSelected"] = { fg = C["error"], bg = C["bg"] },
  ["BufferLineTab"] = { fg = C["comment"], bg = C["bg_gutter"] },
  ["BufferLineTabSelected"] = { fg = C["line_nr_active"], bg = C["bg"], bold = true },
  ["BufferLineTabClose"] = { fg = C["error"], bg = C["bg_gutter"] },
  ["BufferLineTabSeparator"] = { fg = C["bg_gutter"], bg = C["bg_gutter"] },
  ["BufferLineTabSeparatorSelected"] = { fg = C["bg_gutter"], bg = C["bg"] },
  ["BufferLineTruncMarker"] = { fg = C["comment"], bg = C["bg_gutter"] },
  ["BufferLineGroupLabel"] = { fg = C["bg"], bg = C["info"], bold = true },
  ["BufferLineGroupSeparator"] = { fg = C["border"], bg = C["bg_gutter"] },
  ["BufferLineHover"] = { fg = C["fg"], bg = C["bg_cursorline"] },
  ["BufferLinePick"] = { fg = C["error"], bg = C["bg_gutter"], bold = true },
  ["BufferLinePickVisible"] = { fg = C["error"], bg = C["bg_gutter"], bold = true },
  ["BufferLinePickSelected"] = { fg = C["error"], bg = C["bg"], bold = true },
  ["BufferLineError"] = { fg = C["error"], bg = C["bg_gutter"] },
  ["BufferLineErrorVisible"] = { fg = C["error"], bg = C["bg_gutter"] },
  ["BufferLineErrorSelected"] = { fg = C["error"], bg = C["bg"], bold = true },
  ["BufferLineErrorDiagnostic"] = { fg = C["error"], bg = C["bg_gutter"] },
  ["BufferLineErrorDiagnosticVisible"] = { fg = C["error"], bg = C["bg_gutter"] },
  ["BufferLineErrorDiagnosticSelected"] = { fg = C["error"], bg = C["bg"], bold = true },
  ["BufferLineWarning"] = { fg = C["warning"], bg = C["bg_gutter"] },
  ["BufferLineWarningVisible"] = { fg = C["warning"], bg = C["bg_gutter"] },
  ["BufferLineWarningSelected"] = { fg = C["warning"], bg = C["bg"], bold = true },
  ["BufferLineWarningDiagnostic"] = { fg = C["warning"], bg = C["bg_gutter"] },
  ["BufferLineWarningDiagnosticVisible"] = { fg = C["warning"], bg = C["bg_gutter"] },
  ["BufferLineWarningDiagnosticSelected"] = { fg = C["warning"], bg = C["bg"], bold = true },
  ["BufferLineInfo"] = { fg = C["info"], bg = C["bg_gutter"] },
  ["BufferLineInfoVisible"] = { fg = C["info"], bg = C["bg_gutter"] },
  ["BufferLineInfoSelected"] = { fg = C["info"], bg = C["bg"], bold = true },
  ["BufferLineInfoDiagnostic"] = { fg = C["info"], bg = C["bg_gutter"] },
  ["BufferLineInfoDiagnosticVisible"] = { fg = C["info"], bg = C["bg_gutter"] },
  ["BufferLineInfoDiagnosticSelected"] = { fg = C["info"], bg = C["bg"], bold = true },
  ["BufferLineHint"] = { fg = C["hint"], bg = C["bg_gutter"] },
  ["BufferLineHintVisible"] = { fg = C["hint"], bg = C["bg_gutter"] },
  ["BufferLineHintSelected"] = { fg = C["hint"], bg = C["bg"], bold = true },
  ["BufferLineHintDiagnostic"] = { fg = C["hint"], bg = C["bg_gutter"] },
  ["BufferLineHintDiagnosticVisible"] = { fg = C["hint"], bg = C["bg_gutter"] },
  ["BufferLineHintDiagnosticSelected"] = { fg = C["hint"], bg = C["bg"], bold = true },
  -- Snacks: picker, explorer, dashboard, notifier, indent
  ["SnacksPicker"] = { fg = C["fg"], bg = C["bg_float"] },
  ["SnacksPickerBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["SnacksPickerTitle"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["SnacksPickerBoxTitle"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["SnacksPickerInput"] = { fg = C["fg"], bg = C["bg_float"] },
  ["SnacksPickerInputBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["SnacksPickerInputTitle"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["SnacksPickerInputSearch"] = { fg = C["constant"] },
  ["SnacksPickerList"] = { fg = C["fg"], bg = C["bg_float"] },
  ["SnacksPickerListCursorLine"] = { bg = C["bg_pmenu_sel"] },
  ["SnacksPickerPreview"] = { fg = C["fg"], bg = C["bg"] },
  ["SnacksPickerPrompt"] = { fg = C["keyword"], bold = true },
  ["SnacksPickerMatch"] = { fg = C["line_nr_active"], bold = true },
  ["SnacksPickerSearch"] = { fg = C["line_nr_active"], bold = true },
  ["SnacksPickerSelected"] = { fg = C["constant"], bold = true },
  ["SnacksPickerUnselected"] = { fg = C["line_nr"] },
  ["SnacksPickerToggle"] = { fg = C["bg"], bg = C["info"] },
  ["SnacksPickerDir"] = { fg = C["comment"] },
  ["SnacksPickerDirectory"] = { fg = C["function"] },
  ["SnacksPickerFile"] = { fg = C["fg"] },
  ["SnacksPickerPathHidden"] = { fg = C["line_nr"] },
  ["SnacksPickerPathIgnored"] = { fg = C["line_nr"], italic = true },
  ["SnacksPickerDimmed"] = { fg = C["line_nr"] },
  ["SnacksPickerSpecial"] = { fg = C["keyword"] },
  ["SnacksPickerLabel"] = { fg = C["field"] },
  ["SnacksPickerComment"] = { fg = C["comment"], italic = true },
  ["SnacksPickerDesc"] = { fg = C["fg_muted"] },
  ["SnacksPickerIdx"] = { fg = C["constant"] },
  ["SnacksPickerRow"] = { fg = C["line_nr"] },
  ["SnacksPickerCol"] = { fg = C["line_nr"] },
  ["SnacksPickerDelim"] = { fg = C["fg_muted"] },
  ["SnacksPickerTree"] = { fg = C["line_nr"] },
  ["SnacksPickerRule"] = { fg = C["border"] },
  ["SnacksPickerTime"] = { fg = C["comment"] },
  ["SnacksPickerSpinner"] = { fg = C["constant"] },
  ["SnacksPickerTotals"] = { fg = C["comment"] },
  ["SnacksPickerLink"] = { fg = C["info"], underline = true },
  ["SnacksPickerLinkBroken"] = { fg = C["error"], underline = true },
  ["SnacksPickerCode"] = { fg = C["string"] },
  ["SnacksPickerBold"] = { bold = true },
  ["SnacksPickerItalic"] = { italic = true },
  ["SnacksPickerGitBranch"] = { fg = C["keyword"] },
  ["SnacksPickerGitBranchCurrent"] = { fg = C["line_nr_active"], bold = true },
  ["SnacksPickerGitCommit"] = { fg = C["constant"] },
  ["SnacksPickerGitAuthor"] = { fg = C["parameter"] },
  ["SnacksPickerGitDate"] = { fg = C["comment"] },
  ["SnacksPickerGitMsg"] = { fg = C["fg"] },
  ["SnacksPickerGitScope"] = { fg = C["field"] },
  ["SnacksPickerGitType"] = { fg = C["type"] },
  ["SnacksPickerGitBreaking"] = { fg = C["error"], bold = true },
  ["SnacksPickerGitDetached"] = { fg = C["warning"] },
  ["SnacksPickerGitStatusAdded"] = { fg = C["string"] },
  ["SnacksPickerGitStatusModified"] = { fg = C["constant"] },
  ["SnacksPickerGitStatusDeleted"] = { fg = C["error"] },
  ["SnacksPickerGitStatusRenamed"] = { fg = C["info"] },
  ["SnacksPickerGitStatusCopied"] = { fg = C["info"] },
  ["SnacksPickerGitStatusStaged"] = { fg = C["string"] },
  ["SnacksPickerGitStatusUnmerged"] = { fg = C["error"], bold = true },
  ["SnacksPickerGitStatusUntracked"] = { fg = C["line_nr"] },
  ["SnacksPickerDiagnosticCode"] = { fg = C["comment"] },
  ["SnacksPickerDiagnosticSource"] = { fg = C["line_nr"] },
  ["SnacksPickerKeymapLhs"] = { fg = C["constant"] },
  ["SnacksPickerKeymapRhs"] = { fg = C["fg_muted"] },
  ["SnacksPickerKeymapMode"] = { fg = C["keyword"] },
  ["SnacksPickerBufNr"] = { fg = C["line_nr"] },
  ["SnacksPickerBufFlags"] = { fg = C["warning"] },
  ["SnacksDashboard"] = { fg = C["fg"] },
  ["SnacksDashboardNormal"] = { fg = C["fg"], bg = C["bg"] },
  ["SnacksDashboardDesc"] = { fg = C["fg_muted"] },
  ["SnacksDashboardIcon"] = { fg = C["constant"] },
  ["SnacksDashboardKey"] = { fg = C["keyword"], bold = true },
  ["SnacksDashboardHeader"] = { fg = C["line_nr_active"], bold = true },
  ["SnacksDashboardFooter"] = { fg = C["comment"], italic = true },
  ["SnacksDashboardTitle"] = { fg = C["function"], bold = true },
  ["SnacksDashboardDir"] = { fg = C["comment"] },
  ["SnacksDashboardFile"] = { fg = C["fg"] },
  ["SnacksDashboardSpecial"] = { fg = C["keyword"] },
  ["SnacksDashboardTerminal"] = { fg = C["fg"], bg = C["bg"] },
  ["SnacksFooter"] = { fg = C["comment"] },
  ["SnacksFooterKey"] = { fg = C["keyword"], bold = true },
  ["SnacksFooterDesc"] = { fg = C["fg_muted"] },
  ["SnacksNotifierInfo"] = { fg = C["info"], bg = C["bg_vt_info"] },
  ["SnacksNotifierWarn"] = { fg = C["warning"], bg = C["bg_vt_warning"] },
  ["SnacksNotifierError"] = { fg = C["error"], bg = C["bg_vt_error"] },
  ["SnacksNotifierDebug"] = { fg = C["comment"], bg = C["bg_float"] },
  ["SnacksNotifierTrace"] = { fg = C["keyword"], bg = C["bg_float"] },
  ["SnacksNotifierIconInfo"] = { fg = C["info"] },
  ["SnacksNotifierIconWarn"] = { fg = C["warning"] },
  ["SnacksNotifierIconError"] = { fg = C["error"] },
  ["SnacksNotifierTitleInfo"] = { fg = C["info"], bold = true },
  ["SnacksNotifierTitleWarn"] = { fg = C["warning"], bold = true },
  ["SnacksNotifierTitleError"] = { fg = C["error"], bold = true },
  ["SnacksNotifierBorderInfo"] = { fg = C["info"], bg = C["bg_vt_info"] },
  ["SnacksNotifierBorderWarn"] = { fg = C["warning"], bg = C["bg_vt_warning"] },
  ["SnacksNotifierBorderError"] = { fg = C["error"], bg = C["bg_vt_error"] },
  ["SnacksNotifierHistoryTitle"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["SnacksIndent"] = { fg = C["bg_cursorline"] },
  ["SnacksIndentScope"] = { fg = C["keyword"] },
  ["SnacksIndentChunk"] = { fg = C["keyword"] },
  ["SnacksInput"] = { fg = C["fg"], bg = C["bg_float"] },
  ["SnacksInputBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["SnacksInputTitle"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["SnacksInputIcon"] = { fg = C["keyword"] },
  ["SnacksScratch"] = { fg = C["fg"], bg = C["bg_float"] },
  ["SnacksScratchTitle"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["SnacksStatusColumn"] = { fg = C["line_nr"], bg = C["bg_gutter"] },
  ["SnacksStatusColumnMark"] = { fg = C["constant"], bg = C["bg_gutter"] },
  ["SnacksZen"] = { fg = C["fg"], bg = C["bg"] },
  ["SnacksDim"] = { fg = C["line_nr"] },
  ["SnacksWinBar"] = { fg = C["comment"], bg = C["bg_float"] },
  -- Noice: cmdline, popupmenu, confirm
  ["NoiceCmdline"] = { fg = C["fg"], bg = C["bg_float"] },
  ["NoiceCmdlineIcon"] = { fg = C["keyword"] },
  ["NoiceCmdlineIconSearch"] = { fg = C["constant"] },
  ["NoiceCmdlinePopup"] = { fg = C["fg"], bg = C["bg_float"] },
  ["NoiceCmdlinePopupBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["NoiceCmdlinePopupTitle"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["NoiceCmdlinePrompt"] = { fg = C["keyword"], bold = true },
  ["NoiceConfirm"] = { fg = C["fg"], bg = C["bg_float"] },
  ["NoiceConfirmBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["NoicePopup"] = { fg = C["fg"], bg = C["bg_float"] },
  ["NoicePopupBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["NoicePopupmenu"] = { fg = C["fg"], bg = C["bg_float"] },
  ["NoicePopupmenuBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["NoicePopupmenuSelected"] = { bg = C["bg_pmenu_sel"], bold = true },
  ["NoicePopupmenuMatch"] = { fg = C["line_nr_active"], bold = true },
  ["NoiceMini"] = { fg = C["fg"], bg = C["bg_float"] },
  ["NoiceVirtualText"] = { fg = C["comment"], italic = true },
  ["NoiceFormatProgressTodo"] = { bg = C["bg_cursorline"] },
  ["NoiceFormatProgressDone"] = { bg = C["bg_pmenu_sel"] },
  -- Which-key
  ["WhichKey"] = { fg = C["keyword"], bold = true },
  ["WhichKeyGroup"] = { fg = C["function"] },
  ["WhichKeyDesc"] = { fg = C["fg"] },
  ["WhichKeySeparator"] = { fg = C["line_nr"] },
  ["WhichKeyFloat"] = { bg = C["bg_float"] },
  ["WhichKeyBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["WhichKeyTitle"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["WhichKeyValue"] = { fg = C["comment"] },
  ["WhichKeyIcon"] = { fg = C["constant"] },
  ["WhichKeyIconAzure"] = { fg = C["info"] },
  ["WhichKeyIconBlue"] = { fg = C["function"] },
  ["WhichKeyIconCyan"] = { fg = C["type"] },
  ["WhichKeyIconGreen"] = { fg = C["string"] },
  ["WhichKeyIconGrey"] = { fg = C["comment"] },
  ["WhichKeyIconOrange"] = { fg = C["boolean"] },
  ["WhichKeyIconPurple"] = { fg = C["keyword"] },
  ["WhichKeyIconRed"] = { fg = C["error"] },
  ["WhichKeyIconYellow"] = { fg = C["constant"] },
  -- Flash: labels must be unmissable, so they invert like CurSearch
  ["FlashBackdrop"] = { fg = C["line_nr"] },
  ["FlashMatch"] = { fg = C["fg_cursearch"], bg = C["bg_cursearch"] },
  ["FlashCurrent"] = { fg = C["bg"], bg = C["constant"], bold = true },
  ["FlashLabel"] = { fg = C["bg"], bg = C["error"], bold = true },
  ["FlashPrompt"] = { fg = C["fg"], bg = C["bg_float"] },
  ["FlashPromptIcon"] = { fg = C["keyword"] },
  ["FlashCursor"] = { fg = C["bg"], bg = C["fg"] },
  -- blink.cmp
  ["BlinkCmpMenu"] = { fg = C["fg"], bg = C["bg_float"] },
  ["BlinkCmpMenuBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["BlinkCmpMenuSelection"] = { bg = C["bg_pmenu_sel"], bold = true },
  ["BlinkCmpScrollBarThumb"] = { bg = C["border"] },
  ["BlinkCmpScrollBarGutter"] = { bg = C["bg_float"] },
  ["BlinkCmpLabel"] = { fg = C["fg"] },
  ["BlinkCmpLabelDeprecated"] = { fg = C["line_nr"], strikethrough = true },
  ["BlinkCmpLabelMatch"] = { fg = C["line_nr_active"], bold = true },
  ["BlinkCmpLabelDetail"] = { fg = C["comment"] },
  ["BlinkCmpLabelDescription"] = { fg = C["comment"] },
  ["BlinkCmpKind"] = { fg = C["type"] },
  ["BlinkCmpSource"] = { fg = C["line_nr"], italic = true },
  ["BlinkCmpGhostText"] = { fg = C["line_nr"], italic = true },
  ["BlinkCmpDoc"] = { fg = C["fg"], bg = C["bg_float"] },
  ["BlinkCmpDocBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["BlinkCmpDocSeparator"] = { fg = C["border"], bg = C["bg_float"] },
  ["BlinkCmpDocCursorLine"] = { bg = C["bg_pmenu_sel"] },
  ["BlinkCmpSignatureHelp"] = { fg = C["fg"], bg = C["bg_float"] },
  ["BlinkCmpSignatureHelpBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["BlinkCmpSignatureHelpActiveParameter"] = { fg = C["parameter"], bold = true },
  -- Neogit: it derives most colours from the colorscheme already; these are
  -- the few that do not.
  ["NeogitHunkHeader"] = { fg = C["fg_muted"], bg = C["bg_cursorline"] },
  ["NeogitHunkHeaderHighlight"] = { fg = C["line_nr_active"], bg = C["bg_float"], bold = true },
  ["NeogitDiffHeader"] = { fg = C["function"], bg = C["bg_float"], bold = true },
  ["NeogitDiffHeaderHighlight"] = { fg = C["function"], bg = C["bg_float"], bold = true },
  ["NeogitSectionHeader"] = { fg = C["keyword"], bold = true },
  ["NeogitBranch"] = { fg = C["field"], bold = true },
  ["NeogitRemote"] = { fg = C["keyword"], bold = true },
  ["NeogitObjectId"] = { fg = C["constant"] },
  ["NeogitStash"] = { fg = C["boolean"] },
  ["NeogitFold"] = { fg = C["comment"] },
  ["NeogitChangeModified"] = { fg = C["constant"], bold = true },
  ["NeogitChangeAdded"] = { fg = C["string"], bold = true },
  ["NeogitChangeDeleted"] = { fg = C["error"], bold = true },
  ["NeogitChangeRenamed"] = { fg = C["info"], bold = true },
  ["NeogitChangeNewFile"] = { fg = C["string"], bold = true },
  ["NeogitUnmergedInto"] = { fg = C["keyword"], bold = true },
  ["NeogitUnpulledFrom"] = { fg = C["keyword"], bold = true },
  ["NeogitCommitViewHeader"] = { fg = C["bg"], bg = C["info"], bold = true },
  ["NeogitFilePath"] = { fg = C["function"], italic = true },
  -- Mini pick / icons, dressing, grug-far, lazy, mason
  ["MiniPickBorder"] = { fg = C["border"], bg = C["bg_float"] },
  ["MiniPickBorderBusy"] = { fg = C["warning"], bg = C["bg_float"] },
  ["MiniPickBorderText"] = { fg = C["line_nr_active"], bg = C["bg_float"] },
  ["MiniPickNormal"] = { fg = C["fg"], bg = C["bg_float"] },
  ["MiniPickHeader"] = { fg = C["line_nr_active"], bold = true },
  ["MiniPickMatchCurrent"] = { bg = C["bg_pmenu_sel"] },
  ["MiniPickMatchMarked"] = { fg = C["constant"] },
  ["MiniPickMatchRanges"] = { fg = C["line_nr_active"], bold = true },
  ["MiniPickPreviewLine"] = { bg = C["bg_cursorline"] },
  ["MiniPickPreviewRegion"] = { bg = C["bg_visual"] },
  ["MiniPickPrompt"] = { fg = C["keyword"], bg = C["bg_float"], bold = true },
  ["MiniIconsGrey"] = { fg = C["fg_muted"] },
  ["DressingSelectIdx"] = { fg = C["constant"] },
  ["DressingInputText"] = { fg = C["fg"], bg = C["bg_float"] },
  ["GrugFarResultsAddIndicator"] = { fg = C["string"] },
  ["GrugFarResultsRemoveIndicator"] = { fg = C["error"] },
  ["GrugFarResultsChangeIndicator"] = { fg = C["constant"] },
  ["LazyNormal"] = { fg = C["fg"], bg = C["bg_float"] },
  ["LazyButton"] = { fg = C["fg_muted"], bg = C["bg_cursorline"] },
  ["LazyButtonActive"] = { fg = C["bg"], bg = C["info"], bold = true },
  ["LazyH1"] = { fg = C["bg"], bg = C["info"], bold = true },
  ["LazyH2"] = { fg = C["line_nr_active"], bold = true },
  ["MasonNormal"] = { fg = C["fg"], bg = C["bg_float"] },
  ["MasonHeader"] = { fg = C["bg"], bg = C["info"], bold = true },
  ["MasonHighlight"] = { fg = C["field"] },
  ["MasonMuted"] = { fg = C["line_nr"] },
  ["TreesitterContext"] = { bg = C["bg_cursorline"] },
  ["TreesitterContextLineNumber"] = { fg = C["line_nr"], bg = C["bg_cursorline"] },
  ["TreesitterContextBottom"] = { underline = true, sp = C["border"] },

  ["BlinkCmpKindText"] = { fg = C["string"] },
  ["BlinkCmpKindMethod"] = { fg = C["function"] },
  ["BlinkCmpKindFunction"] = { fg = C["function"] },
  ["BlinkCmpKindConstructor"] = { fg = C["type"] },
  ["BlinkCmpKindField"] = { fg = C["field"] },
  ["BlinkCmpKindVariable"] = { fg = C["fg"] },
  ["BlinkCmpKindClass"] = { fg = C["type"] },
  ["BlinkCmpKindInterface"] = { fg = C["type"] },
  ["BlinkCmpKindModule"] = { fg = C["type"] },
  ["BlinkCmpKindProperty"] = { fg = C["field"] },
  ["BlinkCmpKindUnit"] = { fg = C["constant"] },
  ["BlinkCmpKindValue"] = { fg = C["constant"] },
  ["BlinkCmpKindEnum"] = { fg = C["type"] },
  ["BlinkCmpKindKeyword"] = { fg = C["keyword"] },
  ["BlinkCmpKindSnippet"] = { fg = C["boolean"] },
  ["BlinkCmpKindColor"] = { fg = C["parameter"] },
  ["BlinkCmpKindFile"] = { fg = C["fg"] },
  ["BlinkCmpKindReference"] = { fg = C["info"] },
  ["BlinkCmpKindFolder"] = { fg = C["function"] },
  ["BlinkCmpKindEnumMember"] = { fg = C["constant"] },
  ["BlinkCmpKindConstant"] = { fg = C["constant"] },
  ["BlinkCmpKindStruct"] = { fg = C["type"] },
  ["BlinkCmpKindEvent"] = { fg = C["boolean"] },
  ["BlinkCmpKindOperator"] = { fg = C["fg_muted"] },
  ["BlinkCmpKindTypeParameter"] = { fg = C["type"] },
  ["BlinkCmpKindCopilot"] = { fg = C["hint"] },
  ["BlinkCmpKindArray"] = { fg = C["type"] },
  ["BlinkCmpKindBoolean"] = { fg = C["boolean"] },
  ["BlinkCmpKindKey"] = { fg = C["field"] },
  ["BlinkCmpKindNamespace"] = { fg = C["type"] },
  ["BlinkCmpKindNull"] = { fg = C["boolean"] },
  ["BlinkCmpKindNumber"] = { fg = C["constant"] },
  ["BlinkCmpKindObject"] = { fg = C["type"] },
  ["BlinkCmpKindPackage"] = { fg = C["type"] },
  ["BlinkCmpKindString"] = { fg = C["string"] },
  ["LspKindText"] = { fg = C["string"] },
  ["LspKindMethod"] = { fg = C["function"] },
  ["LspKindFunction"] = { fg = C["function"] },
  ["LspKindConstructor"] = { fg = C["type"] },
  ["LspKindField"] = { fg = C["field"] },
  ["LspKindVariable"] = { fg = C["fg"] },
  ["LspKindClass"] = { fg = C["type"] },
  ["LspKindInterface"] = { fg = C["type"] },
  ["LspKindModule"] = { fg = C["type"] },
  ["LspKindProperty"] = { fg = C["field"] },
  ["LspKindUnit"] = { fg = C["constant"] },
  ["LspKindValue"] = { fg = C["constant"] },
  ["LspKindEnum"] = { fg = C["type"] },
  ["LspKindKeyword"] = { fg = C["keyword"] },
  ["LspKindSnippet"] = { fg = C["boolean"] },
  ["LspKindColor"] = { fg = C["parameter"] },
  ["LspKindFile"] = { fg = C["fg"] },
  ["LspKindReference"] = { fg = C["info"] },
  ["LspKindFolder"] = { fg = C["function"] },
  ["LspKindEnumMember"] = { fg = C["constant"] },
  ["LspKindConstant"] = { fg = C["constant"] },
  ["LspKindStruct"] = { fg = C["type"] },
  ["LspKindEvent"] = { fg = C["boolean"] },
  ["LspKindOperator"] = { fg = C["fg_muted"] },
  ["LspKindTypeParameter"] = { fg = C["type"] },
  ["LspKindCopilot"] = { fg = C["hint"] },
  ["LspKindArray"] = { fg = C["type"] },
  ["LspKindBoolean"] = { fg = C["boolean"] },
  ["LspKindKey"] = { fg = C["field"] },
  ["LspKindNamespace"] = { fg = C["type"] },
  ["LspKindNull"] = { fg = C["boolean"] },
  ["LspKindNumber"] = { fg = C["constant"] },
  ["LspKindObject"] = { fg = C["type"] },
  ["LspKindPackage"] = { fg = C["type"] },
  ["LspKindString"] = { fg = C["string"] },
  ["NoiceCompletionItemKindText"] = { fg = C["string"] },
  ["NoiceCompletionItemKindMethod"] = { fg = C["function"] },
  ["NoiceCompletionItemKindFunction"] = { fg = C["function"] },
  ["NoiceCompletionItemKindConstructor"] = { fg = C["type"] },
  ["NoiceCompletionItemKindField"] = { fg = C["field"] },
  ["NoiceCompletionItemKindVariable"] = { fg = C["fg"] },
  ["NoiceCompletionItemKindClass"] = { fg = C["type"] },
  ["NoiceCompletionItemKindInterface"] = { fg = C["type"] },
  ["NoiceCompletionItemKindModule"] = { fg = C["type"] },
  ["NoiceCompletionItemKindProperty"] = { fg = C["field"] },
  ["NoiceCompletionItemKindUnit"] = { fg = C["constant"] },
  ["NoiceCompletionItemKindValue"] = { fg = C["constant"] },
  ["NoiceCompletionItemKindEnum"] = { fg = C["type"] },
  ["NoiceCompletionItemKindKeyword"] = { fg = C["keyword"] },
  ["NoiceCompletionItemKindSnippet"] = { fg = C["boolean"] },
  ["NoiceCompletionItemKindColor"] = { fg = C["parameter"] },
  ["NoiceCompletionItemKindFile"] = { fg = C["fg"] },
  ["NoiceCompletionItemKindReference"] = { fg = C["info"] },
  ["NoiceCompletionItemKindFolder"] = { fg = C["function"] },
  ["NoiceCompletionItemKindEnumMember"] = { fg = C["constant"] },
  ["NoiceCompletionItemKindConstant"] = { fg = C["constant"] },
  ["NoiceCompletionItemKindStruct"] = { fg = C["type"] },
  ["NoiceCompletionItemKindEvent"] = { fg = C["boolean"] },
  ["NoiceCompletionItemKindOperator"] = { fg = C["fg_muted"] },
  ["NoiceCompletionItemKindTypeParameter"] = { fg = C["type"] },
  ["NoiceCompletionItemKindCopilot"] = { fg = C["hint"] },
  ["NoiceCompletionItemKindArray"] = { fg = C["type"] },
  ["NoiceCompletionItemKindBoolean"] = { fg = C["boolean"] },
  ["NoiceCompletionItemKindKey"] = { fg = C["field"] },
  ["NoiceCompletionItemKindNamespace"] = { fg = C["type"] },
  ["NoiceCompletionItemKindNull"] = { fg = C["boolean"] },
  ["NoiceCompletionItemKindNumber"] = { fg = C["constant"] },
  ["NoiceCompletionItemKindObject"] = { fg = C["type"] },
  ["NoiceCompletionItemKindPackage"] = { fg = C["type"] },
  ["NoiceCompletionItemKindString"] = { fg = C["string"] },
  ["CmpItemKindText"] = { fg = C["string"] },
  ["CmpItemKindMethod"] = { fg = C["function"] },
  ["CmpItemKindFunction"] = { fg = C["function"] },
  ["CmpItemKindConstructor"] = { fg = C["type"] },
  ["CmpItemKindField"] = { fg = C["field"] },
  ["CmpItemKindVariable"] = { fg = C["fg"] },
  ["CmpItemKindClass"] = { fg = C["type"] },
  ["CmpItemKindInterface"] = { fg = C["type"] },
  ["CmpItemKindModule"] = { fg = C["type"] },
  ["CmpItemKindProperty"] = { fg = C["field"] },
  ["CmpItemKindUnit"] = { fg = C["constant"] },
  ["CmpItemKindValue"] = { fg = C["constant"] },
  ["CmpItemKindEnum"] = { fg = C["type"] },
  ["CmpItemKindKeyword"] = { fg = C["keyword"] },
  ["CmpItemKindSnippet"] = { fg = C["boolean"] },
  ["CmpItemKindColor"] = { fg = C["parameter"] },
  ["CmpItemKindFile"] = { fg = C["fg"] },
  ["CmpItemKindReference"] = { fg = C["info"] },
  ["CmpItemKindFolder"] = { fg = C["function"] },
  ["CmpItemKindEnumMember"] = { fg = C["constant"] },
  ["CmpItemKindConstant"] = { fg = C["constant"] },
  ["CmpItemKindStruct"] = { fg = C["type"] },
  ["CmpItemKindEvent"] = { fg = C["boolean"] },
  ["CmpItemKindOperator"] = { fg = C["fg_muted"] },
  ["CmpItemKindTypeParameter"] = { fg = C["type"] },
  ["CmpItemKindCopilot"] = { fg = C["hint"] },
  ["CmpItemKindArray"] = { fg = C["type"] },
  ["CmpItemKindBoolean"] = { fg = C["boolean"] },
  ["CmpItemKindKey"] = { fg = C["field"] },
  ["CmpItemKindNamespace"] = { fg = C["type"] },
  ["CmpItemKindNull"] = { fg = C["boolean"] },
  ["CmpItemKindNumber"] = { fg = C["constant"] },
  ["CmpItemKindObject"] = { fg = C["type"] },
  ["CmpItemKindPackage"] = { fg = C["type"] },
  ["CmpItemKindString"] = { fg = C["string"] },
  }

  -- LSP semantic tokens layer on top of Treesitter and win, so each one is
  -- linked explicitly. Skipping this is why themes look correct in one language
  -- and subtly wrong in the next.
  for from, to in pairs({
    ["@lsp.type.class"] = "@type",
    ["@lsp.type.comment"] = "@comment",
    ["@lsp.type.decorator"] = "@attribute",
    ["@lsp.type.enum"] = "@type",
    ["@lsp.type.enumMember"] = "@constant",
    ["@lsp.type.event"] = "@type",
    ["@lsp.type.function"] = "@function",
    ["@lsp.type.interface"] = "@type",
    ["@lsp.type.keyword"] = "@keyword",
    ["@lsp.type.macro"] = "@function.macro",
    ["@lsp.type.method"] = "@function.method",
    ["@lsp.type.modifier"] = "@keyword.modifier",
    ["@lsp.type.namespace"] = "@module",
    ["@lsp.type.number"] = "@number",
    ["@lsp.type.operator"] = "@operator",
    ["@lsp.type.parameter"] = "@variable.parameter",
    ["@lsp.type.property"] = "@property",
    ["@lsp.type.regexp"] = "@string.regexp",
    ["@lsp.type.string"] = "@string",
    ["@lsp.type.struct"] = "@type",
    ["@lsp.type.type"] = "@type",
    ["@lsp.type.typeParameter"] = "@type.definition",
    ["@lsp.type.variable"] = "@variable",
    ["@lsp.mod.readonly"] = "@constant",
    ["@lsp.mod.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
    ["@lsp.typemod.variable.readonly"] = "@constant",
    ["@lsp.typemod.property.readonly"] = "@constant",
  }) do
    g[from] = { link = to }
  end

  return g
end

return M
