# vim: ft=kitty
# tab_bar_style           hidden
tab_bar_edge bottom
tab_bar_style powerline
tab_bar_align center
tab_separator " ┇"
# tab_powerline_style angled
tab_powerline_style slanted

tab_bar_margin_color #4eade1
tab_bar_margin_width -1
tab_bar_margin_height 0 2

# foreground #8A8FA7
tab_bar_background #141D3A

active_tab_background #013A6F
active_tab_foreground #F4F4F4

inactive_tab_background #141D3A
inactive_tab_foreground #013A6F

tab_title_template {fmt.fg.red{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}}
