# Windows > Title Bar
# NOTE: 0=never, 1=always, 2+=when there are that many or more
window_title_bar_min_windows 2

# Windows > Title Bar > Styles
window_title_bar_active_background   #013A6F
window_title_bar_inactive_background #141D3A
window_title_bar_active_foreground   #4EADE1
window_title_bar_inactive_foreground #F4F4F4

## Keybindings
map f12         set_window_title " "
map alt+f12     toggle_window_title_bars
