# Border Colors
# active_border_color #00ff00
# inactive_border_color #cccccc
# bell_border_color #ff5a00

# Cursor
cursor #ebfafa
cursor_text_color #0D1116

# Other
# inactive_text_alpha 1.0

# Symbols
bell_on_tab           "  "
secure_input_symbol   "🔐 "

