return {
  "nvim-treesitter/nvim-treesitter",
  -- lazy = false,
  -- version = "0.*",
  -- build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "css",
      "dockerfile",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "hcl",
      "html",
      "java",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "regex",
      "rust",
      "sql",
      "toml",
      "typescript",
      "yaml",
    },
    highlight = {
      enable = true,
    },
    indent = { enable = true, disable = { "python", "yaml" } },
    -- context_commentstring = {
    --   enable = true,
    --   enable_autocmd = false,
    -- },
  },
}
