return {
  ensure_installed = {
    "bash",
    "dot",
    "gitignore",
    "go",
    "gomod",
    "gowork",
    "graphql",
    "hcl",
    "http",
    "json",
    "jsonnet",
    "lua",
    "make",
    "markdown",
    "python",
    "regex",
    "rust",
    "svelte",
    "swift",
    "toml",
    "typescript",
    "vim",
    "yaml",
  },
  sync_install = false,
  auto_install = true,
  highlight = true,
  additional_vim_regex_highlighting = false,
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "gnn",
      node_incremental = "grn",
      scope_incremental = "grc",
      node_decremental = "grm",
    },
  },
  -- Indent is an experimental feature
  indent = {
    enable = false,
  },
}
