# inserts a blank line between shell prompts
add_newline = true

  # typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%238F╭─'
  # typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%238F├─'
  # typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%238F╰─'
  # # Connect right prompt lines with these symbols.
  # typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX='%238F─╮'
  # typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX='%238F─┤'
  # typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='%238F─╯'

# Put the command duration on the right
right_format = """─╮$cmd_duration─╮"""

# Left Prompt Matterl then put directory and "character" on the second line
format = """╭─$all $fill $cmd_diration...╰─$directory$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[kubernetes]
# format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false

# [aws]
# format = 'on [$symbol($profile )(\($region\) )]($style)'
# style = "bold blue"
# symbol = "🅰 "
# [aws.region_aliases]
# ap-southeast-2 = "au"
# us-east-1 = "va"
