# Keybindings -- `kitty_mod` is `<C-S>` by default
# map f1 toggle_marker iregex 1 \\bERROR\\b 2 \\bWARNING\\b 3 \\bEXCEPTION\\b
map kitty_mod+\ toggle_fullscreen
map f8          launch --title "Today's Notes" --copy-env --type=os-window --cwd ~/notes /Users/rsaska/.local/share/bob/nvim-bin/nvim +YNToday

# Other defaults
# <C-S> f1 = kitty doc overview
# <C-S> f2 = edit kitty config
# <C-S> f3 = command palette
# <C-S> f5 = load config file
#
# <C-S> p ...
#   c   = choose files
#   d   = choose directory
#   f   = [hints] path  (paste to terminal)
#   h   = [hints] hash  (paste to terminal)
#   l   = [hints] line  (paste to terminal)
#   n   = [hints] line number
#   S-f = [hints] path
#   w   = [hints] word  (paste to terminal)
#   y   = [hints] hyperlink
