# Keybindings -- `kitty_mod` is `<C-S>` by default
# map f1 toggle_marker iregex 1 \\bERROR\\b 2 \\bWARNING\\b 3 \\bEXCEPTION\\b
map kitty_mod+\ toggle_fullscreen
map f8          launch --title "Today's Notes" --copy-env --type=os-window --cwd ~/notes /Users/rsaska/.local/share/bob/nvim-bin/nvim +YNToday

